db_url: jdbc:mysql://localhost:3306/productos_db_jpa?user=shop_user&password=shop_pass
db_user: shop_user
db_password: shop_pass

spring:
  application.name: myshoppingcart
  profiles.active: prod

server:
  port: 8080

---

spring:
  config.activate.on-profile: dev
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:mem:myshopDB"
    driverClassName: org.h2.Driver
    username: shop_user
    password: shop_pass
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
      defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-ui

server:
  port: 8080

debug: true

---

spring:
  config.activate.on-profile: prod
  sql.init.mode: always
  datasource:
    url: jdbc:mysql://localhost/productos_db_jpa
    username: shop_user
    password: shop_pass
    driver:
      class: com.mysql.cj.jdbc.Driver
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate.ddl-auto: update

server:
  port: 8443

logging.level.root: ERROR